version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: newsroom-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
      - newsroom-network

  postgres:
    image: postgres:latest
    container_name: newsroom-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=newsroom
    networks:
      - newsroom-network

  redis:
    image: redis:latest
    container_name: newsroom-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - newsroom-network

networks:
  newsroom-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data:
  redis_data:

