groups:
- name: availability
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  - alert: EndpointDown
    expr: probe_success == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Endpoint {{ $labels.instance }} down"
      description: "Endpoint {{ $labels.instance }} is down."

- name: database
  rules:
  - alert: PostgreSQLHighConnections
    expr: sum by (instance) (pg_stat_activity_count) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL high connection count"
      description: "PostgreSQL instance {{ $labels.instance }} has more than 100 connections for 5 minutes."

  - alert: RedisHighMemoryUsage
    expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Redis high memory usage"
      description: "Redis instance {{ $labels.instance }} is using more than 80% of its available memory for 5 minutes."

  - alert: MongoDBHighConnections
    expr: mongodb_connections{state="current"} > 500
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MongoDB high connection count"
      description: "MongoDB instance {{ $labels.instance }} has more than 500 connections for 5 minutes."

- name: system
  rules:
  - alert: HighCPULoad
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU load"
      description: "CPU load is > 80% for 5 minutes on instance {{ $labels.instance }}"

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage is > 80% for 5 minutes on instance {{ $labels.instance }}"

  - alert: HighDiskUsage
    expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High disk usage"
      description: "Disk usage is > 80% for 5 minutes on instance {{ $labels.instance }} mount point {{ $labels.mountpoint }}"

