global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "mongodb_exporter"
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  - job_name: "blackbox_exporter"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://newsroom.example.com
        - https://newsroom-api.modal.run/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

